/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../src/pages/404.vue')['default']
    AsideMenu: typeof import('./../src/layout/aside-menu/aside-menu.vue')['default']
    AsideMenuTree: typeof import('./../src/layout/aside-menu/aside-menu-tree.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./../src/layout/header/index.vue')['default']
    Home: typeof import('./../src/pages/home.vue')['default']
    IMdiSpokenLanguage: typeof import('~icons/mdi/spoken-language')['default']
    Layout: typeof import('./../src/layout/layout.vue')['default']
    Login: typeof import('./../src/pages/login.vue')['default']
    Menus: typeof import('./../src/pages/system/menus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./../src/components/Test.vue')['default']
    UserList: typeof import('./../src/pages/user/user-list.vue')['default']
  }
}
